name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
    - name: Install haxelib dependencies
      run: |
        haxelib git format https://github.com/HaxeFoundation/format.git
        haxelib install hscript
        haxelib install vshaxe
        haxelib install vscode
        haxelib install vscode-debugadapter
    - name: Build extension
      run: make build
    - name: Build CLI hl
      run: |
        cd debugger
        haxe debugger.hxml
        cd ..
    - name: Build standalone adapter.js
      run: haxe build.hxml

